name: Checkmarx AST Scan

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches:
      - main

jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkmarx AST CLI Action
        id: cx_scan
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://ast.checkmarx.net/
          cx_tenant: ${{ secrets.TENANT }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: "--sast-incremental=true --threshold \"sast-high=10; sast-medium=20; sca-critical=10; containers-high=5\""
          source_dir: "."

      - name: Sleep
        if: success()
        run: sleep 10

      - name: Print debugging info
        if: success()
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"

      - name: Extract PR head SHA using GitHub CLI
        if: success()
        id: get_head_sha
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --head "${GITHUB_REF##refs/heads/}" --state open --json number -q '.[0].number')

          if [ -z "$PR_NUMBER" ]; then
            echo "❌ Could not find a matching pull request."
            exit 1
          fi

          HEAD_SHA=$(gh pr view "$PR_NUMBER" --json headRefOid -q .headRefOid)
          echo "✅ PR Head SHA: $HEAD_SHA"
          echo "head_sha=$HEAD_SHA" >> $GITHUB_OUTPUT

      - name: Get Check Run ID for checkmarx-scan
        if: success()
        id: get_check_run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CHECK_RUN_ID=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/commits/${{ steps.get_head_sha.outputs.head_sha }}/check-runs \
            --jq '.check_runs[] | select(.name == "checkmarx-scan") | .id')

          if [ -z "$CHECK_RUN_ID" ]; then
            echo "❌ Check run 'checkmarx-scan' not found."
            exit 1
          fi

          echo "check_run_id=$CHECK_RUN_ID" >> $GITHUB_OUTPUT

      - name: Update Check Run Conclusion to Success
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/check-runs/${{ steps.get_check_run.outputs.check_run_id }} \
            -f status="completed" \
            -f conclusion="success"
