name: Checkmarx AST Scan

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/cxone.yaml'
  pull_request:
    branches:
      - main

jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: https://ast.checkmarx.net/
          cx_tenant: ${{ secrets.TENANT }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: "--sast-incremental=true --threshold \"sast-high=10; sast-medium=20; sca-critical=10; containers-high=5\""
          source_dir: "."  # Change this to your subdirectory if needed
